    df_output, wide_id_vars = process_args_into_dataframe(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AD39644\Desktop\EIS\OneDrive_2024-07-25\Auditing Script\.venv\Lib\site-packages\plotly\express\_core.py", line 1330, in process_args_into_dataframe
    raise ValueError(err_msg)
ValueError: Value of 'names' is not the name of a column in 'data_frame'. Expected one of ['Percentage', 'proportion'] but received: Closure Code 1
