Traceback (most recent call last):
  File "c:\Users\AD39644\Desktop\EIS\OneDrive_2024-07-25\Auditing Script\9200 wr mem missing.py", line 53, in <module>
    wb.save(EXPORT_FILE)
  File "C:\Users\AD39644\Desktop\EIS\OneDrive_2024-07-25\Auditing Script\.venv\Lib\site-packages\openpyxl\workbook\workbook.py", line 386, in save
    save_workbook(self, filename)
  File "C:\Users\AD39644\Desktop\EIS\OneDrive_2024-07-25\Auditing Script\.venv\Lib\site-packages\openpyxl\writer\excel.py", line 294, in save_workbook
    writer.save()
  File "C:\Users\AD39644\Desktop\EIS\OneDrive_2024-07-25\Auditing Script\.venv\Lib\site-packages\openpyxl\writer\excel.py", line 275, in save
    self.write_data()
  File "C:\Users\AD39644\Desktop\EIS\OneDrive_2024-07-25\Auditing Script\.venv\Lib\site-packages\openpyxl\writer\excel.py", line 77, in write_data
    self._write_worksheets()
  File "C:\Users\AD39644\Desktop\EIS\OneDrive_2024-07-25\Auditing Script\.venv\Lib\site-packages\openpyxl\writer\excel.py", line 215, in _write_worksheets
    self.write_worksheet(ws)
  File "C:\Users\AD39644\Desktop\EIS\OneDrive_2024-07-25\Auditing Script\.venv\Lib\site-packages\openpyxl\writer\excel.py", line 200, in write_worksheet
    writer.write()
  File "C:\Users\AD39644\Desktop\EIS\OneDrive_2024-07-25\Auditing Script\.venv\Lib\site-packages\openpyxl\worksheet\_writer.py", line 359, in write
    self.write_rows()
  File "C:\Users\AD39644\Desktop\EIS\OneDrive_2024-07-25\Auditing Script\.venv\Lib\site-packages\openpyxl\worksheet\_writer.py", line 125, in write_rows
    self.write_row(xf, row, row_idx)
  File "C:\Users\AD39644\Desktop\EIS\OneDrive_2024-07-25\Auditing Script\.venv\Lib\site-packages\openpyxl\worksheet\_writer.py", line 147, in write_row
    write_cell(xf, self.ws, cell, cell.has_style)
  File "C:\Users\AD39644\Desktop\EIS\OneDrive_2024-07-25\Auditing Script\.venv\Lib\site-packages\openpyxl\cell\_writer.py", line 47, in etree_write_cell
    value, attributes = _set_attributes(cell, styled)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AD39644\Desktop\EIS\OneDrive_2024-07-25\Auditing Script\.venv\Lib\site-packages\openpyxl\cell\_writer.py", line 30, in _set_attributes
    raise TypeError("Excel does not support timezones in datetimes. "
TypeError: Excel does not support timezones in datetimes. The tzinfo in the datetime/time object must be set to None.
Exception ignored in atexit callback: <function _openpyxl_shutdown at 0x00000271E50684A0>
Traceback (most recent call last):
  File "C:\Users\AD39644\Desktop\EIS\OneDrive_2024-07-25\Auditing Script\.venv\Lib\site-packages\openpyxl\worksheet\_writer.py", line 32, in _openpyxl_shutdown
    os.remove(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Windows\\Temp\\openpyxl.wdrrum4x'
